apiVersion: sailoperator.io/v1alpha1
kind: IstioCNI
metadata:
  name: default
spec:
  version: v1.23.3
  namespace: istio-cni
  profile: ambient
  values:
    cni:
      # Required on OpenShift â€” ambient CNI intercepts traffic at the node level
      ambient:
        enabled: true
